1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [2]:
import numpy as np

In [3]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])          ##зарплата
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])     ##скоринг

In [4]:
b = (np.mean(x*y) - np.mean(x) * np.mean(y)) / (np.mean(x**2) - np.mean(x)**2)  ##1 вариант расчета b
b   

2.620538882402765

In [5]:
n = len(x)                                                                   ##2 вариант расчета b
b = (n * (np.sum(x*y)) - (np.sum(x) * np.sum(y))) / (n * (np.sum(x**2)) - ((np.sum(x)**2)))
b

2.6205388824027653

In [6]:
a = np.mean(y) - b * np.mean(x)
a

444.17735732435955

In [7]:
##матричный метод 2 вариант

In [8]:
x_1 = x.reshape((n,1))
y_1 = y.reshape((n,1))

In [9]:
x_1a = np.hstack([np.ones((n,1)),x_1])   ##добавили столбец с 1-ми, так как есть интерсепт a

In [10]:
b_1_witha = np.dot(np.linalg.inv(np.dot(x_1a.T,x_1a)), x_1a.T@y)
b_1_witha

array([444.17735732,   2.62053888])

In [13]:
y_hat = a + b * x
y_hat

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [82]:
mse = ((y - y_hat)**2).sum()/n
mse                     ##среднеквадратическая ошибка

56516.8584157194

In [83]:
b_1 = np.dot(np.linalg.inv(np.dot(x_1.T,x_1)), x_1.T@y)  ##а это без интерсепта a
b_1

array([5.88982042])

In [84]:
y_hat_1 = b_1 * x
y_hat_1

array([ 206.1437147 ,  265.04191891, 1119.06587983, 1177.96408403,
        235.59281681,  412.28742941,  318.05030269,  883.47306302,
        706.77845042,  647.88024621])

In [85]:
mse = ((y - y_hat_1)**2).sum()/n
mse                     ##среднеквадратическая ошибка

56516.8584157194

2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [78]:
b1 = 5.9       ## начинаем обычно из стандартного нормального распределения от -3 до 3
alpha = 1e-14     ##1/1000000 - скорость обучения (если много - проскочи минимум, мало - не хватит)
n = len(x)

In [79]:
def mse_(b1, y=y, x=x, n=n):
    return np.sum((b1 * x - y)**2) / n

In [ ]:
#mse = (1/n) * np.sum((b1*x-y)**2)  -берем от нее производную
#mse_p = (2/n) * np.sum((b1*x-y)*x)

In [80]:
for i in range(100):
    b1 -= alpha * (2/n) * np.sum((b1 * x - y) * x)
    if i % 10 == 0:
        print('Iteration:{i}, b1 = {b1}, mse = {mse}'.format(i=i, b1=b1, mse=mse_(b1)))

Iteration:0, b1 = 5.8999999999971955, mse = 56518.28599999922
Iteration:10, b1 = 5.899999999969147, mse = 56518.285999991334
Iteration:20, b1 = 5.899999999941098, mse = 56518.285999983476
Iteration:30, b1 = 5.8999999999130495, mse = 56518.28599997563
Iteration:40, b1 = 5.899999999885001, mse = 56518.28599996774
Iteration:50, b1 = 5.899999999856952, mse = 56518.28599995987
Iteration:60, b1 = 5.899999999828903, mse = 56518.285999952
Iteration:70, b1 = 5.899999999800855, mse = 56518.28599994414
Iteration:80, b1 = 5.899999999772806, mse = 56518.28599993627
Iteration:90, b1 = 5.899999999744757, mse = 56518.28599992841


3. В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

In [87]:
## Когда известно средне квадратичное отклонение, то используется таблица значений функции Лапласа,
## когда неизвестно, то таблица критических точек распределения Стьюдента

*4. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [120]:
b1 = 2.6      ## начинаем обычно из стандартного нормального распределения от -3 до 3
alpha = 1e-14     ##1/1000000 - скорость обучения (если много - проскочи минимум, мало - не хватит)
n = len(x)

In [121]:
def mse_(a1, b1, y=y, x=x, n=n):
    return np.sum((a1 + b1 * x - y)**2) / n

In [122]:
for i in range(100):
    b1 -= alpha * (2/n) * np.sum((b1 * x - y) * x)
    a1 = np.mean(y) - b1 * np.mean(x)
    if i % 10 == 0:
        print('Iteration:{i}, b1 = {b1}, a1 = {a1}, mse = {mse}'.format(i=i, b1=b1, a1=a1, mse=mse_(a1, b1)))

Iteration:0, b1 = 2.600000000906451, a1 = 446.25999990808583, mse = 6471.88839986988
Iteration:10, b1 = 2.60000000997096, a1 = 446.25999898894463, mse = 6471.888398568646
Iteration:20, b1 = 2.6000000190354693, a1 = 446.2599980698034, mse = 6471.88839726742
Iteration:30, b1 = 2.6000000280999784, a1 = 446.2599971506622, mse = 6471.888395966193
Iteration:40, b1 = 2.6000000371644876, a1 = 446.2599962315209, mse = 6471.888394664968
Iteration:50, b1 = 2.6000000462289967, a1 = 446.2599953123797, mse = 6471.8883933637435
Iteration:60, b1 = 2.600000055293506, a1 = 446.25999439323846, mse = 6471.888392062518
Iteration:70, b1 = 2.600000064358015, a1 = 446.25999347409726, mse = 6471.888390761293
Iteration:80, b1 = 2.600000073422524, a1 = 446.259992554956, mse = 6471.888389460067
Iteration:90, b1 = 2.6000000824870333, a1 = 446.2599916358148, mse = 6471.888388158846
